baseURL = "https://raisgeo.site/"
languageCode = "id"
title = "The Geographer's Journal"
pagination.pagerSize = 10

[params]
  author = "Rais"
  description = "Notes from every journey"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "JSON"]
